name: Eric Ponto
markdown: redcarpet
highlighter: 'pygments'
safe: false
relative_permalinks: false
exclude: ['README.md', 's3_website.yml', 'node_modules', 'bower.json', '.bowerrc', 'package.json', 'Gruntfile.js']
permalink: /blog/:year/:month/:day/:title/
url: http://ericponto.com
future: false
encoding: utf-8
paginate: 5
paginate_path: "blog/page-:num"
port: 3417
